name: archive_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  geolocator: ^9.0.2
  yandex_mapkit: ^3.2.0
  flutter_bloc: ^8.1.2
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/HelveticaLight.ttf
